name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to compile latex file
    steps:
      - uses: actions/checkout@v1
      - name: Compilation
        uses: tiulpin/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with: 
          tex_path: 'cv.tex'
          push: 'yes'
